Fixed header button
Team-Vibhav/Team-Vibhav.github.io pull request #21
Opened 2020-10-19 15:58 UTC by Yashs911

Fixes #13

2020-10-19 16:18 UTC, Dishebh requested changes

2020-10-19 16:18 UTC, Dishebh commented on index.html
> +<a class="navbar-brand" href="index.html"> <img src="images/logo.png" alt="logo"> </a>
```suggestion
<a class="navbar-brand" href="/"> <img src="images/logo.png" alt="logo"> </a>

```

2020-10-19 16:28 UTC, Yashs911 commented on index.html
> +<a class="navbar-brand" href="index.html"> <img src="images/logo.png" alt="logo"> </a>
Done

2020-10-19 16:35 UTC, Dishebh commented
Please make the same changes in the other links (that you've updated) as well :)

2020-10-19 20:14 UTC, Dishebh requested changes
Do similar changes in all others :)

2020-10-19 20:14 UTC, Dishebh commented on index.html
> +<a class="nav-link" href="index.html">Home</a>
```suggestion
<a class="nav-link" href="/">Home</a>

```

2020-10-19 20:14 UTC, Dishebh commented on index.html
> +<a class="nav-link" href="about.html">about</a>
```suggestion
<a class="nav-link" href="/">about</a>

```

2020-10-19 20:14 UTC, Dishebh commented on index.html
> +<a class="nav-link" href="Causes.html">Causes</a>
```suggestion
<a class="nav-link" href="/">Causes</a>

```

2020-10-19 20:14 UTC, Dishebh commented on index.html
> +<a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
```suggestion
<a class="nav-link dropdown-toggle" href="/" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

```

2020-10-19 20:14 UTC, Dishebh commented on index.html
> +<a href="blog.html">
```suggestion
<a href="/">

```

2020-10-20 14:17 UTC, Dishebh approved these changes

2020-10-20 14:18 UTC, merged